---
# vars file for kubeadm

# https://stackoverflow.com/questions/58169348/how-is-the-architecture-fact-called-in-ansible
deb_architecture:
  armv6l: "armhf"
  armv7l: "armhf"
  aarch64: "arm64"
  x86_64: "amd64"
  i386: "i386"